language: node_js
node_js:
  - 12
cache:
  yarn: true
  directories:
  - node_modules

install:
  - yarn install
script:
  - yarn upgrade
  - yarn build
  - yarn export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  keep_history: true
  local_dir: out

  on:
    branch: main
